version: "3.8"

services:
  api:
    build: ./zare-api
    container_name: zare-api
    ports:
      - "4000:4000"
    volumes:
      - ./zare-api:/app                   # Mount source code for hot-reload
      - zare_node_modules:/app/node_modules  # Prevent overwriting container node_modules
    depends_on:
      - redis
      - rabbitmq
      - elasticsearch
      - postgres
    networks:
      - zare-net
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@postgres:5432/zareshopdb
    command: npm run dev  # Use nodemon for hot-reload

  redis:
    image: redis:7.2
    container_name: zare-redis
    ports:
      - "6379:6379"
    networks:
      - zare-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: zare-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - zare-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: zare-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - zare-net

  postgres:
    image: postgres:15
    container_name: zare-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: zareshopdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zare-net

networks:
  zare-net:
    driver: bridge

volumes:
  pgdata:
  zare_node_modules:
